---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-r2-external-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-r2
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
        AWS_ENDPOINTS: "{{ .endpoints }}"
  data:
    - secretKey: access_key_id
      remoteRef:
        key: longhorn-backup-r2-access-key-id
    - secretKey: secret_access_key
      remoteRef:
        key: longhorn-backup-r2-secret-access-key
    - secretKey: endpoints
      remoteRef:
        key: longhorn-backup-r2-endpoints
