---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-external-secret
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: openclaw-secret
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: openclaw-discord-bot-token
    - secretKey: OPENCODE_API_KEY
      remoteRef:
        key: openclaw-opencode-api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gateway-token-external-secret
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: openclaw-gateway-token-secret
    template:
      type: Opaque
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: openclaw-gateway-token
