---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-external-secret
  namespace: openclaw
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: openclaw-secret
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: openclaw-anthropic-api-key
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: openclaw-discord-bot-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gateway-token-external-secret
  namespace: openclaw
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: openclaw-gateway-token-secret
    template:
      type: Opaque
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
