# pod-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-longhorn-test3
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: pvc-longhorn-test3
