---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirakc
resources:
  - namespace.yaml
  - mirakc-config.yaml
  - mirakc.yaml
  - epgstation-config.yaml
  - epgstation.yaml
  - ingress.yaml
