---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-external-secret
  namespace: dawarich
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: dawarich-secret
    template:
      type: Opaque
      data:
        SECRET_KEY_BASE: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
