---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: milktea
imagePullSecrets:
- name: ghcr-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-auth
  namespace: milktea
spec:
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-auth
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "toof-jp",
                "password": "{{ .pat }}",
                "email": "unused@example.com",
                "auth": "{{ printf "%s:%s" "toof-jp" .pat | b64enc }}"
              }
            }
          }
  data:
  - secretKey: pat
    remoteRef:
      key: ghcr-pat
