---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/toof-jp/infra
      targetRevision: HEAD
      path: kubernetes/applications/headlamp
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: "0.43.0"
      helm:
        valuesObject:
          ingress:
            enabled: true
            ingressClassName: cloudflare-tunnel
            hosts:
              - host: headlamp.toof.jp
                paths:
                  - path: /
                    type: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
