---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          ingress:
            enabled: true
            host: longhorn.toof.jp
            ingressClassName: cloudflare-tunnel
            path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
