---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - external-secret.yaml
  - backup-target.yaml
  - recurring-jobs.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: 1.12.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      defaultSettings:
        taintToleration: node-role.kubernetes.io/control-plane=:NoSchedule
        defaultReplicaCount: 2
        concurrentAutomaticEngineUpgradePerNodeLimit: 1
      persistence:
        defaultClassReplicaCount: 2
      longhornManager:
        tolerations: &controlPlaneToleration
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
      longhornDriver:
        tolerations: *controlPlaneToleration
      longhornUI:
        tolerations: *controlPlaneToleration
      ingress:
        enabled: true
        host: longhorn.toof.jp
        ingressClassName: cloudflare-tunnel
        path: /
