---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-external-secret
  namespace: arc-runners
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: arc-github-app
  data:
    - secretKey: github_app_id
      remoteRef:
        key: arc-github-app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: arc-github-app-installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: arc-github-app-private-key
