---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-runners
resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: arc-dotfiles
    namespace: arc-runners
    valuesFile: arc-dotfiles-values.yaml
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: arc-infra
    namespace: arc-runners
    valuesFile: arc-infra-values.yaml
