---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-secret
            key: secret-access-credentials
            namespace: external-secrets
      projectID: toof-infra
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: infra
      auth:
        serviceAccountSecretRef:
          name: 1password-service-account-secret
          key: token
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 1password-service-account-external-secret
  namespace: external-secrets
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: 1password-service-account-secret
  data:
    - secretKey: token
      remoteRef:
        key: external-secrets-operator-1password-sdk
