---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 42
      digits: 0
      symbols: 0
      symbolCharacters: ""
      allowRepeat: true
