---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: palworld-external-secret
  namespace: palworld
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: palworld-secret
  data:
    - secretKey: SERVER_PASSWORD
      remoteRef:
        key: palworld-server-password
