---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-webhook
  namespace: bbs
spec:
  selector:
    matchLabels:
      app: discord-webhook
  template:
    metadata:
      labels:
        app: discord-webhook
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          command:
            - sh
            - -c
            - until pg_isready -h postgres-rw -p 5432; do sleep 2; done
      containers:
        - name: discord-webhook
          image: ghcr.io/toof-jp/discord-webhook:sha-4319bdc
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: discord-webhook-secret
