---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-post-discord-bot
  namespace: bbs
spec:
  selector:
    matchLabels:
      app: fetch-post-discord-bot
  template:
    metadata:
      labels:
        app: fetch-post-discord-bot
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          command:
            - sh
            - -c
            - until pg_isready -h postgres-rw -p 5432; do sleep 2; done
      containers:
        - name: fetch-post-discord-bot
          image: ghcr.io/toof-jp/bbs-fetch-post-discord-bot:sha-8f9fd09
          env:
            - name: IMAGE_URL_PREFIX
              value: https://d3ixutequkdg55.cloudfront.net/
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: fetch-post-discord-bot-secret
