---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-crawler
  namespace: bbs
spec:
  selector:
    matchLabels:
      app: search-crawler
  template:
    metadata:
      labels:
        app: search-crawler
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          command:
            - sh
            - -c
            - until pg_isready -h postgres-rw -p 5432; do sleep 2; done
      containers:
        - name: search-crawler
          image: ghcr.io/toof-jp/search-crawler:sha-217bd64
          env:
            - name: AWS_REGION
              value: ap-northeast-1
            - name: BUCKET_NAME
              value: oekakiko
          envFrom:
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: search-crawler-secret
