---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
resources:
  - namespace.yaml
  - networkpolicy.yaml
helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp/
    version: 0.43.0
    releaseName: headlamp
    namespace: headlamp
    valuesInline:
      config:
        unsafeUseServiceAccountToken: true
      ingress:
        enabled: true
        ingressClassName: cloudflare-tunnel
        hosts:
          - host: headlamp.toof.jp
            paths:
              - path: /
                type: Prefix
