---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: infra-repository
  namespace: burrito-project
spec:
  repository:
    url: https://github.com/toof-jp/infra
  terraform:
    enabled: true
---
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: infra-layer
  namespace: burrito-project
spec:
  branch: main
  path: terraform
  remediationStrategy:
    autoApply: true
    onError:
      maxRetries: 3
  repository:
    name: infra-repository
    namespace: burrito-project
  overrideRunnerSpec:
    envFrom:
      - secretRef:
          name: terraform-secret
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/gcp/key.json
    volumeMounts:
      - name: terraform-sa-key
        mountPath: /var/secrets/gcp
        readOnly: true
    volumes:
      - name: terraform-sa-key
        secret:
          secretName: terraform-sa-key
          items:
            - key: GOOGLE_CREDENTIALS_JSON
              path: key.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-secret
  namespace: burrito-project
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  target:
    name: terraform-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: terraform/aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: terraform/aws_secret_access_key
    - secretKey: TF_VAR_cloudflare_account_id
      remoteRef:
        key: terraform/cloudflare_account_id
    - secretKey: TF_VAR_cloudflare_api_token
      remoteRef:
        key: terraform/cloudflare_api_token
    - secretKey: TF_VAR_google_billing_account
      remoteRef:
        key: terraform/google_billing_account
    - secretKey: TF_VAR_discord_token
      remoteRef:
        key: terraform/discord_token
    - secretKey: TF_VAR_github_client_id
      remoteRef:
        key: terraform/github_clitent_id
    - secretKey: TF_VAR_github_client_secret
      remoteRef:
        key: terraform/github_client_secret
    - secretKey: TF_VAR_tfe_email
      remoteRef:
        key: terraform/tfe_email
    - secretKey: TF_VAR_tfe_oauth_token_id
      remoteRef:
        key: terraform/tfe_oauth_token_id
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-sa-key
  namespace: burrito-project
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: terraform-sa-key
  data:
    - secretKey: GOOGLE_CREDENTIALS_JSON
      remoteRef:
        key: terraform-service-account-key
        decodingStrategy: Base64
